fieldLayouts:
  6a8433fd-28a0-44ba-96f5-3c63cb24aa2f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dbf5607a-a0b6-482e-9375-c88f55207b7d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b25c5e7e-fa61-4d6f-99ea-519b93f058a5 # Bilder
            instructions: null
            label: 'Ein Bild'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b00b6e3-a983-434e-9f14-92f834d2bbcc
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 6a047a97-1fb5-4e21-a2c1-c2554a02a84b
        userCondition: null
handle: einzelbild
hasTitleField: true
name: Einzelbild
section: 6a085986-e262-4a23-9922-0fb08df43973 # Projekte
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
