fieldLayouts:
  7cb89c75-ce43-43e0-9d35-41254d05b0da:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 02768ce9-4585-49ca-87ae-815f79a7e986
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: fb4824f8-9aa1-4d70-a753-6d6bc6a71a28
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
