columnSuffix: null
contentColumnType: string
fieldGroup: ffb26aef-ae68-4bbf-b19c-9e287242ed75 # Common
handle: images
instructions: null
name: Bilder
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:fc0b7718-6b35-4edb-a329-5607ff2cb072' # Uploads
  defaultUploadLocationSubpath: 'bilder/{slug}'
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 2
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:fc0b7718-6b35-4edb-a329-5607ff2cb072' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: 'Bild wählen'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:fc0b7718-6b35-4edb-a329-5607ff2cb072' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
