columnSuffix: tidfbjul
contentColumnType: text
fieldGroup: ffb26aef-ae68-4bbf-b19c-9e287242ed75 # Common
handle: vimeoId
instructions: 'Vimeo-Code (nicht die ganze URL)'
name: Vimeo-ID
searchable: false
settings:
  url: ''
translationKeyFormat: null
translationMethod: none
type: wrav\oembed\fields\OembedField
